load("@bazel_latex//:latex.bzl", "latex_document")

latex_document(
    name = "script",
    srcs = [
        "@bazel_latex//packages:listings",
        "@bazel_latex//packages:xcolor",
    ],
    main = "main.tex",
)
