py_binary(
    name = "decode_enumerator",
    srcs = ["enumerator.py"],
    main = "enumerator.py",
)

py_test(
    name = "decode_enumerator_test",
    srcs = ["test_enumerator.py"],
    deps = [":decode_enumerator"],
    main = "test_enumerator.py",
)